### Site settings ###

title: "Resume"
email: "henry.lu@mail.utoronto.ca"
name: "Henry Lu"
url: "https://github.com/nanosmasher"
baseurl: "/resume/"
markdown: "kramdown"
permalink: '/resume/:title/'
exclude: ["LICENSE_MATERIALIZE","README.md","README_MATERIALIZE.md"]

description: "Resume for Henry Lu"

social:
    -   name: "facebook"
        url: "https://facebook.com/henry.lu.5030"
    -   name: "github"
        url: "https://github.com/nanosmasher"